version: '2.4'

volumes:
  postgres_data_local: {}
  postgres_backup_local: {}

services:

  squarelet_nginx:
    image: nginx:latest
    depends_on:
      - squarelet_mailhog
    volumes:
      - ./compose/local/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

  squarelet_mailhog:
    image: mailhog/mailhog:v1.0.0
    networks:
      default:
        aliases:
          - dev.mailhog.com

  squarelet_django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: squarelet_local_django
    depends_on:
      - squarelet_postgres
      - squarelet_mailhog
      - squarelet_nginx
    volumes:
      - .:/app
      - ~/.netrc:/root/.netrc
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    command: /start
    networks:
      default:
        aliases:
          - dev.squarelet.com
          - dev.presspass.com
          - dev.squarelet.local

  squarelet_postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: squarelet_production_postgres
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
      - postgres_backup_local:/backups
    env_file:
      - ./.envs/.local/.postgres

  squarelet_redis:
    image: redis:3.2

  squarelet_celeryworker:
    <<: *django
    image: squarelet_local_celeryworker
    depends_on:
      - squarelet_redis
      - squarelet_postgres
      - squarelet_mailhog
    command: /start-celeryworker
    networks:
      default:
        aliases: []

  squarelet_celerybeat:
    <<: *django
    image: squarelet_local_celerybeat
    depends_on:
      - squarelet_redis
      - squarelet_postgres
      - squarelet_mailhog
    command: /start-celerybeat
    networks:
      default:
        aliases: []

networks:
  default:
    name: "squarelet_default"
